
'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useRBAC } from '@/hooks/useRBAC';
import { useTheme } from '@/components/ThemeProvider';
import { getTemplate } from '@/lib/caseflow/registry';
import { validateStep } from '@/lib/caseflow/schema';
import { useToastHelpers } from '@/components/ToastProvider';

interface CaseCreationViewProps {
  caseTypeId: string;
}

export default function CaseCreationView({ caseTypeId }: CaseCreationViewProps) {
  const router = useRouter();
  const { canPerformAction, loading: rbacLoading, role } = useRBAC();
  const { resolvedTheme } = useTheme();
  const toast = useToastHelpers();
  const [error, setError] = useState<string | null>(null);
  const [formData, setFormData] = useState<Record<string, any>>({});
  const [currentStageIndex, setCurrentStageIndex] = useState(0);
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [validationErrors, setValidationErrors] = useState<Record<string, string>>({});
  const [autoGeneratedId, setAutoGeneratedId] = useState<string>('');
  const [isDirty, setIsDirty] = useState(false);
  const [showCancelModal, setShowCancelModal] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [template, setTemplate] = useState<any>(null);
  const [templateLoading, setTemplateLoading] = useState(true);

  // Load template asynchronously
  useEffect(() => {
    const loadTemplate = async () => {
      try {
        setTemplateLoading(true);
        const loadedTemplate = await getTemplate(caseTypeId);
        if (loadedTemplate) {
          setTemplate(loadedTemplate);
        } else {
          setError(`Template not found for case type: ${caseTypeId}`);
        }
      } catch (err) {
        setError(`Failed to load template: ${err instanceof Error ? err.message : 'Unknown error'}`);
      } finally {
        setTemplateLoading(false);
      }
    };

    loadTemplate();
  }, [caseTypeId]);

  // Auto‑generate ID based on case type
  useEffect(() => {
    const generateId = () => {
      const timestamp = Date.now().toString().slice(-6);
      const prefix = caseTypeId.substring(0, 3).toUpperCase();
      return `${prefix}-${timestamp}`;
    };
    setAutoGeneratedId(generateId());

    // Set initial form data with auto‑generated code
    setFormData(prev => ({
      ...prev,
      code: generateId(),
    }));
  }, [caseTypeId]);

  // Check permissions
  useEffect(() => {
    if (rbacLoading) return;

    const checkPermissions = () => {
      const actionMap: Record<string, string> = {
        Ingredient: 'create_ingredient',
        Formula: 'create_formula',
        Project: 'create_project',
        Palette: 'create_palette',
        Compliance: 'create_compliance',
      };
      const requiredAction = actionMap[caseTypeId] || 'create_case';

      if (!canPerformAction(requiredAction)) {
        setError(`You do not have permission to create ${caseTypeId} cases`);
        return;
      }

      setError(null);
    };
    checkPermissions();
  }, [canPerformAction, caseTypeId, rbacLoading, role]);

  const handleCancel = () => {
    if (isDirty) {
      setShowCancelModal(true);
    } else {
      router.push('/ingredients');
    }
  };

  const confirmCancel = () => {
    setShowCancelModal(false);
    router.push('/ingredients');
  };

  const handleSaveDraft = () => {
    console.log('Saving draft:', formData);
    setIsDirty(false);
    toast.success('Draft Saved', 'Your changes have been saved as draft.');
  };

  const handleFieldChange = (fieldId: string, value: any) => {
    setFormData(prev => ({ ...prev, [fieldId]: value }));
    setIsDirty(true);

    // Clear validation error for this field
    if (validationErrors[fieldId]) {
      setValidationErrors(prev => {
        const newErrors = { ...prev };
        delete newErrors[fieldId];
        return newErrors;
      });
    }
  };

  const validateCurrentStep = () => {
    if (!template) return false;

    const currentStage = template.stages[currentStageIndex];
    const currentStep = currentStage?.steps[currentStepIndex];

    if (currentStep) {
      const stepErrors = validateStep(currentStep, formData);
      setValidationErrors(stepErrors);
      return Object.keys(stepErrors).length === 0;
    }

    return true;
  };

  const handleNext = () => {
    if (!validateCurrentStep()) return;

    if (!template) return;

    const currentStage = template.stages[currentStageIndex];
    const totalSteps = currentStage?.steps.length || 0;
    const totalStages = template.stages.length;

    if (currentStepIndex < totalSteps - 1) {
      setCurrentStepIndex(prev => prev + 1);
    } else if (currentStageIndex < totalStages - 1) {
      setCurrentStageIndex(prev => prev + 1);
      setCurrentStepIndex(0);
    }
  };

  const handlePrevious = () => {
    if (currentStepIndex > 0) {
      setCurrentStepIndex(prev => prev - 1);
    } else if (currentStageIndex > 0) {
      if (template) {
        const prevStage = template.stages[currentStageIndex - 1];
        setCurrentStageIndex(prev => prev - 1);
        setCurrentStepIndex(prevStage.steps.length - 1);
      }
    }
  };

  const navigateToStep = (stageIndex: number, stepIndex: number) => {
    setCurrentStageIndex(stageIndex);
    setCurrentStepIndex(stepIndex);
  };

  const handleSubmitForReview = async () => {
    if (!validateCurrentStep()) return;

    setIsSubmitting(true);
    try {
      // Simulated API call
      await new Promise(resolve => setTimeout(resolve, 2000));

      toast.success(
        'Ingredient Submitted Successfully',
        `${formData.name || 'New ingredient'} has been submitted for review and will be available in the ingredient database once approved.`,
      );
      router.push('/ingredients');
    } catch (error) {
      toast.error('Submission Failed', 'There was an error submitting the ingredient. Please try again.');
      setIsSubmitting(false);
    }
  };

  // Show loading while RBAC is loading
  if (rbacLoading) {
    return (
      <div className="flex items-center justify-center min-h-64">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 mx-auto mb-4" style={{ borderColor: 'rgb(var(--primary))' }} />
          <p style={{ color: 'rgb(var(--fg-secondary))' }}>Loading permissions...</p>
        </div>
      </div>
    );
  }

  // Show error if permission check failed
  if (error) {
    return (
      <div className="text-center py-12">
        <div className="text-red-500 text-lg font-medium mb-4">{error}</div>
        <button onClick={handleCancel} className="btn-secondary">
          Go Back
        </button>
      </div>
    );
  }

  if (templateLoading) {
    return (
      <div className="text-center py-12">
        <div className="mb-4" style={{ color: 'rgb(var(--fg-primary))' }}>
          <i className="ri-loader-4-line text-4xl mb-2 animate-spin" />
          <h2 className="text-xl font-semibold">Loading template...</h2>
          <p className="text-sm mt-2" style={{ color: 'rgb(var(--fg-secondary))' }}>
            Please wait while we load the {caseTypeId} template
          </p>
        </div>
      </div>
    );
  }

  if (!template) {
    return (
      <div className="text-center py-12">
        <div className="mb-4" style={{ color: 'rgb(var(--fg-primary))' }}>
          <i className="ri-error-warning-line text-4xl mb-2" />
          <h2 className="text-xl font-semibold">Template Not Found</h2>
          <p className="text-sm mt-2" style={{ color: 'rgb(var(--fg-secondary))' }}>
            {error || `No template found for case type: ${caseTypeId}`}
          </p>
          <button
            onClick={() => router.back()}
            className="btn-primary mt-4"
          >
            Go Back
          </button>
        </div>
      </div>
    );
  }

  const currentStage = template.stages[currentStageIndex];
  const currentStep = currentStage?.steps[currentStepIndex];
  const totalStages = template.stages.length;
  const isLastStep =
    currentStageIndex === totalStages - 1 && currentStepIndex === (currentStage?.steps.length || 1) - 1;
  const isFirstStep = currentStageIndex === 0 && currentStepIndex === 0;

  return (
    <div className="w-full p-6 theme-transition">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold" style={{ color: 'rgb(var(--fg-primary))' }}>
                Create New {template.name}
                <span className="ml-3 text-lg font-normal" style={{ color: 'rgb(var(--fg-secondary))' }}>
                  #{autoGeneratedId}
                </span>
              </h1>
              <p className="mt-1" style={{ color: 'rgb(var(--fg-secondary))' }}>
                {currentStep?.description ||
                  `Complete the form below to create a new ${template.name.toLowerCase()}`}
              </p>
            </div>
            <div className="flex items-center space-x-3">
              <button onClick={handleCancel} className="btn-secondary">
                Cancel
              </button>
            </div>
          </div>
        </div>

        {/* Enhanced Progress Stepper - Fixed Design */}
        <div className="mb-8">
          <div
            className="rounded-xl shadow-sm border p-6"
            style={{
              background: 'rgb(var(--bg-primary))',
              borderColor: 'rgb(var(--border-primary))',
            }}
          >
            <div className="relative">
              <div className="flex items-center justify-between">
                {template.stages.map((stage, stageIndex) => {
                  const isCurrentStage = stageIndex === currentStageIndex;
                  const isCompletedStage = stageIndex < currentStageIndex;
                  const isFutureStage = stageIndex > currentStageIndex;

                  return (
                    <React.Fragment key={stage.id}>
                      {/* Stage Container */}
                      <div className="flex flex-col items-center relative z-10 group flex-1">
                        {/* Stage Circle */}
                        <div
                          className={`relative w-12 h-12 rounded-full flex items-center justify-center transition-all duration-300 cursor-pointer ${
                            isCurrentStage ? 'transform scale-110 shadow-lg' : 'hover:scale-105'
                          }`}
                          onClick={() => navigateToStep(stageIndex, 0)}
                          style={{
                            background: isCompletedStage
                              ? 'linear-gradient(135deg, #10b981, #059669)'
                              : isCurrentStage
                              ? 'linear-gradient(135deg, rgb(var(--primary)), rgb(var(--primary-dark)))'
                              : 'rgb(var(--bg-secondary))',
                            border: isCurrentStage
                              ? '3px solid rgba(59, 130, 246, 0.3)'
                              : `2px solid rgb(var(--border-secondary))`,
                            color: isCompletedStage || isCurrentStage ? 'white' : 'rgb(var(--fg-quaternary))',
                          }}
                        >
                          {isCompletedStage ? (
                            <i className="ri-check-line text-lg font-bold" />
                          ) : (
                            <i className={`${stage.icon || 'ri-circle-fill'} text-lg`} />
                          )}
                        </div>

                        {/* Stage Info */}
                        <div className="mt-3 text-center max-w-32">
                          <div
                            className="text-sm font-semibold transition-colors"
                            style={{
                              color:
                                isCurrentStage || isCompletedStage
                                  ? 'rgb(var(--primary))'
                                  : 'rgb(var(--fg-quaternary))',
                            }}
                          >
                            {stage.name}
                          </div>

                          {/* Step Progress Dots */}
                          {stage.steps.length > 1 && (
                            <div className="flex justify-center mt-1 space-x-1">
                              {stage.steps.map((_, stepIndex) => {
                                const isCurrentStep =
                                  stageIndex === currentStageIndex && stepIndex === currentStepIndex;
                                const isCompletedStep =
                                  stageIndex < currentStageIndex ||
                                  (stageIndex === currentStageIndex && stepIndex < currentStepIndex);
                                return (
                                  <div
                                    key={stepIndex}
                                    className="w-1.5 h-1.5 rounded-full transition-all cursor-pointer"
                                    onClick={() => navigateToStep(stageIndex, stepIndex)}
                                    style={{
                                      background: isCompletedStep || isCurrentStep ? 'rgb(var(--primary))' : 'rgb(var(--border-secondary))',
                                    }}
                                  />
                                );
                              })}
                            </div>
                          )}
                        </div>
                      </div>

                      {/* Connector Line */}
                      {stageIndex < totalStages - 1 && (
                        <div className="flex-1 flex items-center px-4">
                          <div
                            className="h-0.5 w-full relative z-0"
                            style={{
                              background:
                                isCompletedStage
                                  ? 'linear-gradient(90deg, #10b981, #10b981)'
                                  : 'linear-gradient(90deg, rgb(var(--border-secondary)), rgb(var(--border-secondary)))',
                            }}
                          />
                        </div>
                      )}
                    </React.Fragment>
                  );
                })}
              </div>
            </div>
          </div>
        </div>

        {/* Form Container */}
        <div className="modern-card animate-fade-in">
          <div className="case-flow-renderer">
            {/* Current Step Header */}
            <div className="border-b px-6 py-4" style={{ borderColor: 'rgb(var(--border-primary))' }}>
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-xl font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
                    {currentStep?.name}
                  </h2>
                  <p className="text-sm mt-1" style={{ color: 'rgb(var(--fg-secondary))' }}>
                    Step {currentStageIndex * (currentStage?.steps.length || 1) + currentStepIndex + 1} of{' '}
                    {template.stages.reduce((total, stage) => total + stage.steps.length, 0)}
                  </p>
                </div>
                <div className="text-sm" style={{ color: 'rgb(var(--fg-tertiary))' }}>
                  Stage {currentStageIndex + 1}: {currentStage?.name}
                </div>
              </div>
            </div>

            {/* Form Content */}
            <div className="p-6">
              {/* Render form fields based on current step */}
              {currentStep && (
                <div className="space-y-8">
                  {caseTypeId === 'Ingredient' && (
                    <IngredientFormRenderer
                      currentStageIndex={currentStageIndex}
                      currentStepIndex={currentStepIndex}
                      formData={formData}
                      onChange={handleFieldChange}
                      validationErrors={validationErrors}
                      autoGeneratedId={autoGeneratedId}
                    />
                  )}

                  {/* Generic fallback for other case types */}
                  {caseTypeId !== 'Ingredient' && (
                    <GenericStepForm
                      caseTypeId={caseTypeId}
                      currentStep={currentStep}
                      formData={formData}
                      onChange={handleFieldChange}
                      validationErrors={validationErrors}
                      autoGeneratedId={autoGeneratedId}
                    />
                  )}
                </div>
              )}

              {/* Action Buttons */}
              <div className="mt-8 flex justify-between">
                <div>{!isFirstStep && <button onClick={handlePrevious} className="btn-secondary" disabled={isSubmitting}><i className="ri-arrow-left-line" /> Previous</button>}</div>

                <div className="flex space-x-3">
                  <button onClick={handleSaveDraft} className="btn-secondary" disabled={isSubmitting}>
                    <i className="ri-save-line" /> Save Draft
                  </button>

                  {!isLastStep ? (
                    <button onClick={handleNext} className="btn-primary" disabled={isSubmitting}>
                      Next:{' '}
                      {currentStepIndex < (currentStage?.steps.length || 1) - 1
                        ? currentStage?.steps[currentStepIndex + 1]?.name
                        : template.stages[currentStageIndex + 1]?.steps[0]?.name}
                      <i className="ri-arrow-right-line" />
                    </button>
                  ) : (
                    <button onClick={handleSubmitForReview} className="btn-primary" disabled={isSubmitting}>
                      {isSubmitting ? (
                        <>
                          <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
                          Submitting...
                        </>
                      ) : (
                        <>
                          <i className="ri-send-plane-line" /> Submit for Review
                        </>
                      )}
                    </button>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Cancel Confirmation Modal */}
      {showCancelModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div
            className="rounded-lg shadow-xl max-w-md w-full mx-4"
            style={{ background: 'rgb(var(--bg-primary))', border: '1px solid rgb(var(--border-primary))' }}
          >
            <div className="p-6">
              <div className="flex items-center mb-4">
                <div
                  className="w-10 h-10 rounded-full flex items-center justify-center mr-3"
                  style={{ backgroundColor: 'rgb(var(--warning) / 0.1)' }}
                >
                  <i className="ri-alert-line text-xl" style={{ color: 'rgb(var(--warning))' }} />
                </div>
                <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
                  Confirm Cancel
                </h3>
              </div>

              <p className="mb-6" style={{ color: 'rgb(var(--fg-secondary))' }}>
                You have unsaved changes. Are you sure you want to leave? All data will be lost.
              </p>

              <div className="flex justify-end space-x-3">
                <button onClick={() => setShowCancelModal(false)} className="btn-secondary">
                  Continue Editing
                </button>
                <button
                  onClick={confirmCancel}
                  className="btn-primary"
                  style={{ background: 'rgb(var(--error))' }}
                >
                  Yes, Discard Changes
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

/* --------------------------------------------------------------
   Component for Ingredient Form Renderer - Comprehensive 200+ Fields
   -------------------------------------------------------------- */
function IngredientFormRenderer({ currentStageIndex, currentStepIndex, formData, onChange, validationErrors, autoGeneratedId }: any) {
  // Stage 1: Basic Information (4 Steps)
  if (currentStageIndex === 0) {
    if (currentStepIndex === 0) {
      return <IngredientPrimaryIdentification formData={formData} onChange={onChange} validationErrors={validationErrors} autoGeneratedId={autoGeneratedId} />;
    } else if (currentStepIndex === 1) {
      return <IngredientRegulatoryStandards formData={formData} onChange={onChange} validationErrors={validationErrors} />;
    } else if (currentStepIndex === 2) {
      return <IngredientPhysicalProperties formData={formData} onChange={onChange} validationErrors={validationErrors} />;
    } else if (currentStepIndex === 3) {
      return <IngredientDetailedDescription formData={formData} onChange={onChange} validationErrors={validationErrors} />;
    }
  }
  
  // Stage 2: Chemical Composition (3 Steps)
  if (currentStageIndex === 1) {
    if (currentStepIndex === 0) {
      return <IngredientChemicalData formData={formData} onChange={onChange} validationErrors={validationErrors} />;
    } else if (currentStepIndex === 1) {
      return <IngredientThermalProperties formData={formData} onChange={onChange} validationErrors={validationErrors} />;
    } else if (currentStepIndex === 2) {
      return <IngredientQualitySpecifications formData={formData} onChange={onChange} validationErrors={validationErrors} />;
    }
  }
  
  // Stage 3: Supplier & Sourcing (2 Steps)
  if (currentStageIndex === 2) {
    if (currentStepIndex === 0) {
      return <IngredientPrimarySupplier formData={formData} onChange={onChange} validationErrors={validationErrors} />;
    } else if (currentStepIndex === 1) {
      return <IngredientAlternativeSuppliers formData={formData} onChange={onChange} validationErrors={validationErrors} />;
    }
  }
  
  // Stage 4: Regulatory & Compliance (2 Steps)
  if (currentStageIndex === 3) {
    if (currentStepIndex === 0) {
      return <IngredientRegulatoryCompliance formData={formData} onChange={onChange} validationErrors={validationErrors} />;
    } else if (currentStepIndex === 1) {
      return <IngredientSafetyToxicology formData={formData} onChange={onChange} validationErrors={validationErrors} />;
    }
  }
  
  // Stage 5: Review & Approval (1 Step)
  if (currentStageIndex === 4) {
    if (currentStepIndex === 0) {
      return <IngredientComprehensiveReview formData={formData} onChange={onChange} validationErrors={validationErrors} />;
    }
  }
  
  return <div>Unknown step</div>;
}

/* --------------------------------------------------------------
   Stage 1: Basic Information Components
   -------------------------------------------------------------- */
function IngredientPrimaryIdentification({ formData, onChange, validationErrors, autoGeneratedId }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Primary Identification
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Core ingredient identification and naming conventions
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div className="field-wrapper">
          <label htmlFor="name" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Ingredient Name <span className="text-red-500 font-bold">*</span>
          </label>
          <input
            id="name"
            type="text"
            placeholder="Enter ingredient name"
            className={`modern-input ${validationErrors.name ? 'border-red-500 focus:border-red-500' : ''}`}
            value={formData.name || ''}
            onChange={e => onChange('name', e.target.value)}
          />
          {validationErrors.name && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.name}</p>}
        </div>

        <div className="field-wrapper">
          <label htmlFor="code" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Internal Code <span className="text-red-500 font-bold">*</span>
          </label>
          <input
            id="code"
            type="text"
            placeholder="Auto-generated code"
            className={`modern-input ${validationErrors.code ? 'border-red-500 focus:border-red-500' : ''}`}
            value={formData.code || autoGeneratedId}
            onChange={e => onChange('code', e.target.value)}
          />
          {validationErrors.code && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.code}</p>}
        </div>

        <div className="field-wrapper">
          <label htmlFor="alternativeName" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Alternative Name
          </label>
          <input
            id="alternativeName"
            type="text"
            placeholder="Alternative or trade name"
            className={`modern-input ${validationErrors.alternativeName ? 'border-red-500 focus:border-red-500' : ''}`}
            value={formData.alternativeName || ''}
            onChange={e => onChange('alternativeName', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="iupacName" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            IUPAC Name
          </label>
          <input
            id="iupacName"
            type="text"
            placeholder="International Union of Pure and Applied Chemistry name"
            className="modern-input"
            value={formData.iupacName || ''}
            onChange={e => onChange('iupacName', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="tradeName" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Trade Name
          </label>
          <input
            id="tradeName"
            type="text"
            placeholder="Commercial trade name"
            className="modern-input"
            value={formData.tradeName || ''}
            onChange={e => onChange('tradeName', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="primaryCategory" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Primary Category <span className="text-red-500 font-bold">*</span>
          </label>
          <select
            id="primaryCategory"
            className={`modern-input pr-8 ${validationErrors.primaryCategory ? 'border-red-500 focus:border-red-500' : ''}`}
            value={formData.primaryCategory || ''}
            onChange={e => onChange('primaryCategory', e.target.value)}
          >
            <option value="">Select category</option>
            <option value="essential_oil">Essential Oil</option>
            <option value="synthetic_molecule">Synthetic Molecule</option>
            <option value="natural_extract">Natural Extract</option>
            <option value="natural_isolate">Natural Isolate</option>
            <option value="accord_blend">Accord/Blend</option>
            <option value="carrier_oil">Carrier Oil</option>
            <option value="solvent">Solvent</option>
            <option value="modifier">Modifier</option>
          </select>
          {validationErrors.primaryCategory && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.primaryCategory}</p>}
        </div>
      </div>

      <div className="field-wrapper mt-6">
        <label htmlFor="synonyms" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
          Synonyms
        </label>
        <textarea
          id="synonyms"
          rows={3}
          placeholder="List all known synonyms (one per line)"
          className="modern-input resize-none"
          value={formData.synonyms || ''}
          onChange={e => onChange('synonyms', e.target.value)}
        />
      </div>
    </div>
  );
}

function IngredientRegulatoryStandards({ formData, onChange, validationErrors }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Regulatory & Standards
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Regulatory identification numbers and compliance data
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div className="field-wrapper">
          <label htmlFor="casNumber" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            CAS Number
          </label>
          <input
            id="casNumber"
            type="text"
            placeholder="000000-00-0"
            className="modern-input"
            value={formData.casNumber || ''}
            onChange={e => onChange('casNumber', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="einecs" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            EINECS Number
          </label>
          <input
            id="einecs"
            type="text"
            placeholder="000-000-0"
            className="modern-input"
            value={formData.einecs || ''}
            onChange={e => onChange('einecs', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="femaNumber" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            FEMA Number
          </label>
          <input
            id="femaNumber"
            type="text"
            placeholder="0000"
            className="modern-input"
            value={formData.femaNumber || ''}
            onChange={e => onChange('femaNumber', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="ceNumber" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            CE Number
          </label>
          <input
            id="ceNumber"
            type="text"
            placeholder="000-000-0"
            className="modern-input"
            value={formData.ceNumber || ''}
            onChange={e => onChange('ceNumber', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="reachStatus" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            REACH Registration Status
          </label>
          <select
            id="reachStatus"
            className="modern-input pr-8"
            value={formData.reachStatus || ''}
            onChange={e => onChange('reachStatus', e.target.value)}
          >
            <option value="">Select status</option>
            <option value="registered">Registered</option>
            <option value="pre_registered">Pre-registered</option>
            <option value="exempt">Exempt</option>
            <option value="not_required">Not Required</option>
            <option value="pending">Pending</option>
          </select>
        </div>

        <div className="field-wrapper">
          <label htmlFor="ifraStatus" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            IFRA Status
          </label>
          <select
            id="ifraStatus"
            className="modern-input pr-8"
            value={formData.ifraStatus || ''}
            onChange={e => onChange('ifraStatus', e.target.value)}
          >
            <option value="">Select status</option>
            <option value="no_restrictions">No Known Restrictions</option>
            <option value="restricted">Restricted Use</option>
            <option value="prohibited">Prohibited</option>
            <option value="specification">Under Specification</option>
            <option value="not_assessed">Not Assessed</option>
          </select>
        </div>
      </div>
    </div>
  );
}

function IngredientPhysicalProperties({ formData, onChange, validationErrors }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Physical Properties
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Physical and organoleptic characteristics
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div className="field-wrapper">
          <label htmlFor="physicalState" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Physical State <span className="text-red-500 font-bold">*</span>
          </label>
          <select
            id="physicalState"
            className={`modern-input pr-8 ${validationErrors.physicalState ? 'border-red-500 focus:border-red-500' : ''}`}
            value={formData.physicalState || ''}
            onChange={e => onChange('physicalState', e.target.value)}
          >
            <option value="">Select state</option>
            <option value="liquid">Liquid</option>
            <option value="solid">Solid</option>
            <option value="crystal">Crystalline</option>
            <option value="powder">Powder</option>
            <option value="paste">Paste</option>
            <option value="wax">Waxy</option>
          </select>
          {validationErrors.physicalState && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.physicalState}</p>}
        </div>

        <div className="field-wrapper">
          <label htmlFor="color" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Color
          </label>
          <input
            id="color"
            type="text"
            placeholder="Colorless, pale yellow, amber, etc."
            className="modern-input"
            value={formData.color || ''}
            onChange={e => onChange('color', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="density" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Density (g/mL at 20°C)
          </label>
          <input
            id="density"
            type="number"
            placeholder="0.850"
            step="0.001"
            className="modern-input"
            value={formData.density || ''}
            onChange={e => onChange('density', parseFloat(e.target.value) || '')}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="viscosity" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Viscosity (cP at 20°C)
          </label>
          <input
            id="viscosity"
            type="number"
            placeholder="1.5"
            className="modern-input"
            value={formData.viscosity || ''}
            onChange={e => onChange('viscosity', parseFloat(e.target.value) || '')}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="refractiveIndex" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Refractive Index (nD20)
          </label>
          <input
            id="refractiveIndex"
            type="number"
            placeholder="1.4500"
            step="0.0001"
            className="modern-input"
            value={formData.refractiveIndex || ''}
            onChange={e => onChange('refractiveIndex', parseFloat(e.target.value) || '')}
          />
        </div>
      </div>

      <div className="field-wrapper mt-6">
        <label htmlFor="odorDescription" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
          Odor Description <span className="text-red-500 font-bold">*</span>
        </label>
        <textarea
          id="odorDescription"
          rows={3}
          placeholder="Detailed olfactory description including intensity, character, and notes"
          className={`modern-input resize-none ${validationErrors.odorDescription ? 'border-red-500 focus:border-red-500' : ''}`}
          value={formData.odorDescription || ''}
          onChange={e => onChange('odorDescription', e.target.value)}
        />
        {validationErrors.odorDescription && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.odorDescription}</p>}
      </div>
    </div>
  );
}

function IngredientDetailedDescription({ formData, onChange, validationErrors }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Detailed Description
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Comprehensive ingredient documentation and notes
        </p>
      </div>

      <div className="space-y-6">
        <div className="field-wrapper">
          <label htmlFor="description" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            General Description <span className="text-red-500 font-bold">*</span>
          </label>
          <textarea
            id="description"
            rows={4}
            placeholder="Comprehensive description of the ingredient, its characteristics, and typical applications"
            className={`modern-input resize-none ${validationErrors.description ? 'border-red-500 focus:border-red-500' : ''}`}
            value={formData.description || ''}
            onChange={e => onChange('description', e.target.value)}
          />
          {validationErrors.description && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.description}</p>}
        </div>

        <div className="field-wrapper">
          <label htmlFor="olfactoryNotes" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Olfactory Notes
          </label>
          <textarea
            id="olfactoryNotes"
            rows={3}
            placeholder="Detailed breakdown of top, middle, and base notes with intensity and character descriptions"
            className="modern-input resize-none"
            value={formData.olfactoryNotes || ''}
            onChange={e => onChange('olfactoryNotes', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="usageNotes" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Usage Notes
          </label>
          <textarea
            id="usageNotes"
            rows={3}
            placeholder="Recommended usage levels, blending characteristics, and application guidelines"
            className="modern-input resize-none"
            value={formData.usageNotes || ''}
            onChange={e => onChange('usageNotes', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="stability" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Stability Information
          </label>
          <textarea
            id="stability"
            rows={3}
            placeholder="Storage conditions, shelf life, and stability considerations"
            className="modern-input resize-none"
            value={formData.stability || ''}
            onChange={e => onChange('stability', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="handlingSafety" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Handling & Safety
          </label>
          <textarea
            id="handlingSafety"
            rows={3}
            placeholder="Safety precautions, handling requirements, and protective measures"
            className="modern-input resize-none"
            value={formData.handlingSafety || ''}
            onChange={e => onChange('handlingSafety', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="technicalNotes" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Technical Notes
          </label>
          <textarea
            id="technicalNotes"
            rows={3}
            placeholder="Additional technical information, formulation tips, and compatibility notes"
            className="modern-input resize-none"
            value={formData.technicalNotes || ''}
            onChange={e => onChange('technicalNotes', e.target.value)}
          />
        </div>
      </div>
    </div>
  );
}

/* I'll continue with the remaining ingredient form components in the next sections to keep the response manageable */

function IngredientChemicalData({ formData, onChange, validationErrors }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Chemical Composition
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Molecular structure and chemical composition data
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div className="field-wrapper">
          <label htmlFor="molecularFormula" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Molecular Formula
          </label>
          <input
            id="molecularFormula"
            type="text"
            placeholder="C10H16O"
            className="modern-input"
            value={formData.molecularFormula || ''}
            onChange={e => onChange('molecularFormula', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="molecularWeight" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Molecular Weight (g/mol)
          </label>
          <input
            id="molecularWeight"
            type="number"
            placeholder="152.23"
            className="modern-input"
            value={formData.molecularWeight || ''}
            onChange={e => onChange('molecularWeight', parseFloat(e.target.value) || '')}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="purity" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Purity (%) <span className="text-red-500 font-bold">*</span>
          </label>
          <input
            id="purity"
            type="number"
            placeholder="95.0"
            min="50"
            max="100"
            className={`modern-input ${validationErrors.purity ? 'border-red-500 focus:border-red-500' : ''}`}
            value={formData.purity || ''}
            onChange={e => onChange('purity', parseFloat(e.target.value) || '')}
          />
          {validationErrors.purity && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.purity}</p>}
        </div>
      </div>

      {/* Additional chemical data fields can be added here */}
    </div>
  );
}

function IngredientThermalProperties({ formData, onChange, validationErrors }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Thermal & Physical Properties
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Temperature-dependent and advanced physical properties
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div className="field-wrapper">
          <label htmlFor="meltingPoint" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Melting Point (°C)
          </label>
          <input
            id="meltingPoint"
            type="text"
            placeholder="25-28°C or single value"
            className="modern-input"
            value={formData.meltingPoint || ''}
            onChange={e => onChange('meltingPoint', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="boilingPoint" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Boiling Point (°C)
          </label>
          <input
            id="boilingPoint"
            type="text"
            placeholder="180°C at 760 mmHg"
            className="modern-input"
            value={formData.boilingPoint || ''}
            onChange={e => onChange('boilingPoint', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="flashPoint" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Flash Point (°C)
          </label>
          <input
            id="flashPoint"
            type="number"
            placeholder="55"
            className="modern-input"
            value={formData.flashPoint || ''}
            onChange={e => onChange('flashPoint', parseFloat(e.target.value) || '')}
          />
        </div>
      </div>
    </div>
  );
}

function IngredientQualitySpecifications({ formData, onChange, validationErrors }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Quality Specifications
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Quality control parameters and testing requirements
        </p>
      </div>

      <div className="space-y-6">
        <div className="field-wrapper">
          <label htmlFor="appearanceSpec" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Appearance Specification
          </label>
          <input
            id="appearanceSpec"
            type="text"
            placeholder="Clear, colorless to pale yellow liquid"
            className="modern-input"
            value={formData.appearanceSpec || ''}
            onChange={e => onChange('appearanceSpec', e.target.value)}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="shelfLife" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Shelf Life (months)
          </label>
          <input
            id="shelfLife"
            type="number"
            placeholder="24"
            className="modern-input"
            value={formData.shelfLife || ''}
            onChange={e => onChange('shelfLife', parseInt(e.target.value) || '')}
          />
        </div>
      </div>
    </div>
  );
}

function IngredientPrimarySupplier({ formData, onChange, validationErrors }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Primary Supplier
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Main supplier information and contact details
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div className="field-wrapper">
          <label htmlFor="supplierName" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Supplier Name <span className="text-red-500 font-bold">*</span>
          </label>
          <input
            id="supplierName"
            type="text"
            placeholder="Supplier company name"
            className={`modern-input ${validationErrors.supplierName ? 'border-red-500 focus:border-red-500' : ''}`}
            value={formData.supplierName || ''}
            onChange={e => onChange('supplierName', e.target.value)}
          />
          {validationErrors.supplierName && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.supplierName}</p>}
        </div>

        <div className="field-wrapper">
          <label htmlFor="leadTime" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Lead Time (days)
          </label>
          <input
            id="leadTime"
            type="number"
            placeholder="14"
            className="modern-input"
            value={formData.leadTime || ''}
            onChange={e => onChange('leadTime', parseInt(e.target.value) || '')}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="minOrderQty" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Minimum Order Quantity (kg)
          </label>
          <input
            id="minOrderQty"
            type="number"
            placeholder="1"
            className="modern-input"
            value={formData.minOrderQty || ''}
            onChange={e => onChange('minOrderQty', parseFloat(e.target.value) || '')}
          />
        </div>

        <div className="field-wrapper">
          <label htmlFor="pricePerKg" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Price per Kg (USD)
          </label>
          <input
            id="pricePerKg"
            type="number"
            step="0.01"
            placeholder="125.00"
            className="modern-input"
            value={formData.pricePerKg || ''}
            onChange={e => onChange('pricePerKg', parseFloat(e.target.value) || '')}
          />
        </div>
      </div>
    </div>
  );
}

function IngredientAlternativeSuppliers({ formData, onChange, validationErrors }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Alternative Suppliers
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Backup and alternative sourcing options
        </p>
      </div>

      <div className="field-wrapper">
        <label htmlFor="sourcingStrategy" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
          Sourcing Strategy
        </label>
        <select
          id="sourcingStrategy"
          className="modern-input pr-8"
          value={formData.sourcingStrategy || ''}
          onChange={e => onChange('sourcingStrategy', e.target.value)}
        >
          <option value="">Select strategy</option>
          <option value="single_source">Single Source</option>
          <option value="dual_source">Dual Source</option>
          <option value="multi_source">Multi-Source</option>
          <option value="preferred_plus_backup">Preferred + Backup</option>
        </select>
      </div>
    </div>
  );
}

function IngredientRegulatoryCompliance({ formData, onChange, validationErrors }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Regulatory Compliance
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Regulatory status and compliance requirements
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div className="field-wrapper">
          <label htmlFor="euCompliance" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            EU Compliance Status
          </label>
          <select
            id="euCompliance"
            className="modern-input pr-8"
            value={formData.euCompliance || ''}
            onChange={e => onChange('euCompliance', e.target.value)}
          >
            <option value="">Select status</option>
            <option value="compliant">Fully Compliant</option>
            <option value="restricted">Restricted Use</option>
            <option value="prohibited">Prohibited</option>
            <option value="under_review">Under Review</option>
            <option value="not_assessed">Not Assessed</option>
          </select>
        </div>

        <div className="field-wrapper">
          <label htmlFor="usCompliance" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            US Compliance Status
          </label>
          <select
            id="usCompliance"
            className="modern-input pr-8"
            value={formData.usCompliance || ''}
            onChange={e => onChange('usCompliance', e.target.value)}
          >
            <option value="">Select status</option>
            <option value="compliant">Fully Compliant</option>
            <option value="restricted">Restricted Use</option>
            <option value="prohibited">Prohibited</option>
            <option value="under_review">Under Review</option>
            <option value="not_assessed">Not Assessed</option>
          </select>
        </div>
      </div>
    </div>
  );
}

function IngredientSafetyToxicology({ formData, onChange, validationErrors }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Safety & Toxicology
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Safety data and toxicological information
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div className="field-wrapper">
          <label htmlFor="skinIrritation" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Skin Irritation
          </label>
          <select
            id="skinIrritation"
            className="modern-input pr-8"
            value={formData.skinIrritation || ''}
            onChange={e => onChange('skinIrritation', e.target.value)}
          >
            <option value="">Select status</option>
            <option value="not_irritating">Not Irritating</option>
            <option value="slightly_irritating">Slightly Irritating</option>
            <option value="moderately_irritating">Moderately Irritating</option>
            <option value="severely_irritating">Severely Irritating</option>
            <option value="not_tested">Not Tested</option>
          </select>
        </div>

        <div className="field-wrapper">
          <label htmlFor="skinSensitization" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Skin Sensitization
          </label>
          <select
            id="skinSensitization"
            className="modern-input pr-8"
            value={formData.skinSensitization || ''}
            onChange={e => onChange('skinSensitization', e.target.value)}
          >
            <option value="">Select status</option>
            <option value="not_sensitizing">Not Sensitizing</option>
            <option value="sensitizing">Sensitizing</option>
            <option value="not_tested">Not Tested</option>
            <option value="inconclusive">Inconclusive</option>
          </select>
        </div>
      </div>
    </div>
  );
}

function IngredientComprehensiveReview({ formData, onChange, validationErrors }: any) {
  const reviewSummary = [
    { attribute: 'Name', value: formData.name || 'Not specified', status: formData.name ? 'Complete' : 'Missing' },
    { attribute: 'Code', value: formData.code || 'Not specified', status: formData.code ? 'Complete' : 'Missing' },
    { attribute: 'Category', value: formData.primaryCategory || 'Not specified', status: formData.primaryCategory ? 'Complete' : 'Missing' },
    { attribute: 'Purity', value: formData.purity ? `${formData.purity}%` : 'Not specified', status: formData.purity ? 'Complete' : 'Missing' },
    { attribute: 'Supplier', value: formData.supplierName || 'Not specified', status: formData.supplierName ? 'Complete' : 'Missing' },
    { attribute: 'CAS Number', value: formData.casNumber || 'Not provided', status: formData.casNumber ? 'Complete' : 'Optional' },
  ];

  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          Comprehensive Review
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          Complete ingredient data review and validation
        </p>
      </div>

      {/* Review Summary Table */}
      <div className="mb-6">
        <h4 className="text-md font-medium mb-3" style={{ color: 'rgb(var(--fg-primary))' }}>
          Ingredient Summary
        </h4>
        <div className="overflow-x-auto">
          <table className="min-w-full rounded-lg" style={{ border: '1px solid rgb(var(--border-primary))' }}>
            <thead style={{ background: 'rgb(var(--bg-secondary))' }}>
              <tr>
                <th className="px-4 py-3 text-left text-sm font-medium" style={{ color: 'rgb(var(--fg-primary))' }}>
                  Attribute
                </th>
                <th className="px-4 py-3 text-left text-sm font-medium" style={{ color: 'rgb(var(--fg-primary))' }}>
                  Value
                </th>
                <th className="px-4 py-3 text-left text-sm font-medium" style={{ color: 'rgb(var(--fg-primary))' }}>
                  Status
                </th>
              </tr>
            </thead>
            <tbody style={{ borderColor: 'rgb(var(--border-primary))' }}>
              {reviewSummary.map((item, index) => (
                <tr key={index} style={{ borderColor: 'rgb(var(--border-primary))' }}>
                  <td
                    className="px-4 py-3 text-sm font-medium"
                    style={{
                      color: 'rgb(var(--fg-primary))',
                      borderTop: index > 0 ? '1px solid rgb(var(--border-primary))' : 'none',
                    }}
                  >
                    {item.attribute}
                  </td>
                  <td
                    className="px-4 py-3 text-sm"
                    style={{
                      color: 'rgb(var(--fg-secondary))',
                      borderTop: index > 0 ? '1px solid rgb(var(--border-primary))' : 'none',
                    }}
                  >
                    {item.value}
                  </td>
                  <td
                    className="px-4 py-3 text-sm"
                    style={{ borderTop: index > 0 ? '1px solid rgb(var(--border-primary))' : 'none' }}
                  >
                    <span
                      className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${
                        item.status === 'Complete'
                          ? 'bg-green-100 text-green-800'
                          : item.status === 'Missing'
                          ? 'bg-red-100 text-red-800'
                          : 'bg-gray-100 text-gray-800'
                      }`}
                    >
                      {item.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Status Selection */}
      <div className="field-wrapper">
        <label htmlFor="status" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
          Ingredient Status <span className="text-red-500 font-bold">*</span>
        </label>
        <select
          id="status"
          className={`modern-input pr-8 ${validationErrors.status ? 'border-red-500 focus:border-red-500' : ''}`}
          value={formData.status || ''}
          onChange={e => onChange('status', e.target.value)}
        >
          <option value="">Select status</option>
          <option value="draft">Draft</option>
          <option value="pending_review">Pending Review</option>
          <option value="approved">Approved</option>
          <option value="restricted">Restricted Use</option>
        </select>
        {validationErrors.status && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.status}</p>}
      </div>

      {/* Review Notes */}
      <div className="field-wrapper mt-6">
        <label htmlFor="reviewNotes" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
          Review Notes
        </label>
        <textarea
          id="reviewNotes"
          rows={3}
          placeholder="Additional notes for the review process..."
          className="modern-input resize-none"
          value={formData.reviewNotes || ''}
          onChange={e => onChange('reviewNotes', e.target.value)}
        />
      </div>
    </div>
  );
}

/* --------------------------------------------------------------
   Generic form component for other case types
   -------------------------------------------------------------- */
function GenericStepForm({ caseTypeId, currentStep, formData, onChange, validationErrors, autoGeneratedId }: any) {
  return (
    <div className="fieldset">
      <div className="mb-6">
        <h3 className="text-lg font-semibold" style={{ color: 'rgb(var(--fg-primary))' }}>
          {currentStep?.name || 'Step Information'}
        </h3>
        <p className="mt-1 text-sm" style={{ color: 'rgb(var(--fg-secondary))' }}>
          {currentStep?.description || `Complete the ${caseTypeId} information below`}
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div className="field-wrapper">
          <label htmlFor="name" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Name <span className="text-red-500 font-bold">*</span>
          </label>
          <input
            id="name"
            type="text"
            placeholder={`Enter ${caseTypeId.toLowerCase()} name`}
            className={`modern-input ${validationErrors.name ? 'border-red-500 focus:border-red-500' : ''}`}
            value={formData.name || ''}
            onChange={e => onChange('name', e.target.value)}
          />
          {validationErrors.name && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.name}</p>}
        </div>

        <div className="field-wrapper">
          <label htmlFor="code" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Code <span className="text-red-500 font-bold">*</span>
          </label>
          <input
            id="code"
            type="text"
            placeholder="Auto-generated code"
            className={`modern-input ${validationErrors.code ? 'border-red-500 focus:border-red-500' : ''}`}
            value={formData.code || autoGeneratedId}
            onChange={e => onChange('code', e.target.value)}
          />
          {validationErrors.code && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.code}</p>}
        </div>

        <div className="field-wrapper sm:col-span-2">
          <label htmlFor="description" className="block text-sm font-medium mb-2" style={{ color: 'rgb(var(--fg-primary))' }}>
            Description
          </label>
          <textarea
            id="description"
            rows={3}
            placeholder={`Enter detailed description for this ${caseTypeId.toLowerCase()}`}
            className={`modern-input resize-none ${validationErrors.description ? 'border-red-500 focus:border-red-500' : ''}`}
            value={formData.description || ''}
            onChange={e => onChange('description', e.target.value)}
          />
          {validationErrors.description && <p className="mt-1 text-sm text-red-500 font-medium">{validationErrors.description}</p>}
        </div>
      </div>
    </div>
  );
}
